<?php

declare(strict_types=1);

return [
    'id' => 'mailcom',
    'name' => 'Mail.com',
    'domains' => [
        'mail.com',
        'email.com',
        'usa.com',
        'myself.com',
        'consultant.com',
        'engineer.com',
        'europe.com',
        'asia.com',
        'post.com',
        'dr.com',
        'myself.com',
        'writeme.com',
        'workmail.com',
        'techie.com',
        'cheerful.com',
        'accountant.com',
        'alumni.com',
        'attorney.com',
        'chef.net',
        'comic.com',
        'doctor.com',
        'execs.com',
        'financier.com',
        'gardener.com',
        'journalist.com',
        'lawyer.com',
        'minister.com',
        'musician.org',
        'photographer.net',
        'programmer.net',
        'publicist.com',
        'teachers.org',
        'technologist.com',
        'therapist.net',
        'webname.com',
        'worker.com',
    ],
];
